# Generated by Django 5.1.4 on 2026-06-12 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("latitude", models.FloatField(db_index=True)),
                ("longitude", models.FloatField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
                "permissions": (
                    ("export_sensorlog", "Can export sensor log records"),
                    ("view_livedata", "Can access real-time data streams"),
                    ("view_visualization", "Can view charts/visualizations"),
                    ("view_organization_data", "Can view data for own organization"),
                    ("view_all_data", "Can view data across all organizations"),
                ),
            },
        ),
        migrations.CreateModel(
            name="Robot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "robot_id_str",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable unique ID, e.g. 'RANGER-PRIME-001'.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OFFLINE", "Offline"),
                            ("ONLINE", "Online"),
                            ("MISSION", "On mission"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        default="OFFLINE",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SensorType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.SlugField(
                        help_text="Stable machine identifier, e.g. 'geiger', 'pm', 'imu_baro'.",
                        unique=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Primary unit of measurement, e.g. 'CPM', 'µg/m³'.",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AirQualityLog",
            fields=[
                (
                    "sensor_log",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="air_quality_data",
                        serialize=False,
                        to="core.sensorlog",
                    ),
                ),
                (
                    "pm25",
                    models.FloatField(blank=True, help_text="PM2.5 µg/m³.", null=True),
                ),
                (
                    "pm10",
                    models.FloatField(blank=True, help_text="PM10 µg/m³.", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImuBaroLog",
            fields=[
                (
                    "sensor_log",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="imu_baro_data",
                        serialize=False,
                        to="core.sensorlog",
                    ),
                ),
                ("roll", models.FloatField(blank=True, null=True)),
                ("pitch", models.FloatField(blank=True, null=True)),
                ("yaw", models.FloatField(blank=True, null=True)),
                (
                    "pressure_baro",
                    models.FloatField(blank=True, help_text="hPa.", null=True),
                ),
                (
                    "altitude_baro",
                    models.FloatField(blank=True, help_text="Metres.", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RadiationLog",
            fields=[
                (
                    "sensor_log",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="radiation_data",
                        serialize=False,
                        to="core.sensorlog",
                    ),
                ),
                (
                    "radiation_value",
                    models.FloatField(help_text="Counts per minute (CPM)."),
                ),
                (
                    "dose_rate_usvh",
                    models.FloatField(
                        blank=True, help_text="Dose rate in µSv/h.", null=True
                    ),
                ),
            ],
        ),
    ]
