# Generated by Django 5.1.4 on 2026-06-12 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("core", "0001_initial"),
        ("missions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensorlog",
            name="mission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sensor_logs",
                to="missions.mission",
            ),
        ),
        migrations.AddField(
            model_name="sensorlog",
            name="robot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensor_logs",
                to="core.robot",
            ),
        ),
        migrations.AddField(
            model_name="robot",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="robots",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="robot",
            name="installed_sensors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Which sensor types are physically installed on this robot.",
                related_name="robots",
                to="core.sensortype",
            ),
        ),
    ]
